Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.hostname = "arch"

  config.vm.network :private_network, ip: "192.168.10.12"
  config.vm.network:forwarded_port,guest:80,host:7008,auto_correct:true
  config.vm.network:forwarded_port,guest:8080,host:7088,auto_correct:true

end
