global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:

- job_name: 'core-m.workfusion.com'
  static_configs:
  - targets: ['localhost:9090','core-m.workfusion.com:9100']

- job_name: 'jenkins'
  metrics_path: '/prometheus/'
  scheme: https
  static_configs:
    - targets: ['jenkins.workfusion.com:443']
