#================
#===== если пизданулись значки - то проблема в fonts в iterm переставить на SourceCodePro+Powerline+Awesome Regular 
export ZSH=$HOME/.oh-my-zsh
export TERM="screen-256color"

#========| THEME SETTINGS |===========
ZSH_THEME="spaceship"
LS_COLORS=$LS_COLORS:'di=1;35:' ; export LS_COLORS

SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  elixir        # Elixir section
  xcode         # Xcode section
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  venv          # virtualenv section
  conda         # conda virtualenv section
  pyenv         # Pyenv section
  dotnet        # .NET section
  ember         # Ember.js section
  kubecontext   # Kubectl context section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

#setopt SPACESHIP_TIME_SHOW 

#==========| ZSH SETTINGS |=============
plugins=(
zsh-autosuggestions
zsh-syntax-highlighting
git
)

#Seperate history for sessions
#setopt APPEND_HISTORY #SHARED history!!
#setopt INC_APPEND_HISTORY
#searching in history will skip duplicate entries
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS

# NO FUCKING SHARING HISTORY!!!!!!!!!!!!!
unsetopt share_history

#Alert if bg jobs running
setopt CHECK_JOBS
#Info about bg jobs
setopt NOTIFY

source $ZSH/oh-my-zsh.sh

#=========CUSTOM_FUNCTIONS========

# === | ALIAS | ===
alias zshrc="vim ~/.zshrc"
alias szshrc='source ~/.zshrc'
alias ohmyzsh="vim ~/.oh-my-zsh"
alias trc='tree -C'
alias trp='tree -Cpu'
alias trd='tree -C -d'
alias clc='clear'
alias weather='curl wttr.in/Minsk'
alias subl='open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias rm='rmtrash' 

#========Exports=========
#
export MANPATH="/usr/local/man:$MANPATH"

#Pyenv
export PYENV_ROOT="$HOME/.pyenv"

#JAVA
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home"

# Gettext
export PATH="/usr/local/opt/gettext/bin:$PATH"

# GCloud SDK
export PATH=$PATH:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin

# GNU
export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

export PATH
export PATH="/usr/local/sbin:$PATH"
