#================
#===== если пизданулись значки - то проблема в fonts в iterm переставить на SourceCodePro+Powerline+Awesome Regular 
export ZSH=$HOME/.oh-my-zsh
export TERM="screen-256color"

#========| THEME SETTINGS |===========
ZSH_THEME="spaceship"
LS_COLORS=$LS_COLORS:'di=1;35:' ; export LS_COLORS

#==========| ZSH SETTINGS |=============
plugins=(
vi-mode
osx
git
docker
zsh-autosuggestions
zsh-syntax-highlighting
)


# NO FUCKING SHARING HISTORY!!!!!!!!!!!!!
unsetopt inc_append_history
unsetopt share_history

#Alert if bg jobs running
setopt CHECK_JOBS
#Info about bg jobs
setopt NOTIFY

source $ZSH/oh-my-zsh.sh

#=========CUSTOM_FUNCTIONS========

# === | ALIAS | ===

alias zshrc="vim ~/.zshrc"
alias szshrc='source ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias svimrc='source ~/.vimrc'
alias ohmyzsh="vim ~/.oh-my-zsh"
alias trc='tree -C'
alias trp='tree -Cpu'
alias trd='tree -C -d'
alias clc='clear'
alias weather='curl wttr.in/Minsk'
alias subl='open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias rm='rmtrash' 
alias rand='cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 32 | head -n'
alias sshconf='vim ~/.ssh/config'
alias tmuxrc='vim ~/.tmux.conf'
alias ip='curl ifconfig.co'

#========Exports=========
#
export MANPATH="/usr/local/man:$MANPATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home"
export JRE_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre"
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
export PATH=$PATH:$GOPATH/bin


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/amaslakou/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/amaslakou/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/amaslakou/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/amaslakou/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
