#================
#===== если пизданулись значки - то проблема в fonts в iterm переставить на SourceCodePro+Powerline+Awesome Regular 
export ZSH=$HOME/.oh-my-zsh
export TERM="screen-256color"

#========| THEME SETTINGS |===========
ZSH_THEME="spaceship"
LS_COLORS=$LS_COLORS:'di=1;35:' ; export LS_COLORS

#==========| ZSH SETTINGS |=============
plugins=(
vi-mode
osx
git
docker
zsh-autosuggestions
zsh-syntax-highlighting
)


#SPACESHIP_VI_MODE_COLOR=949494

#Seperate history for sessions
#setopt APPEND_HISTORY #SHARED history!!
#setopt INC_APPEND_HISTORY
#searching in history will skip duplicate entries
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS

# NO FUCKING SHARING HISTORY!!!!!!!!!!!!!
unsetopt share_history

#Alert if bg jobs running
setopt CHECK_JOBS
#Info about bg jobs
setopt NOTIFY

source $ZSH/oh-my-zsh.sh

#=========CUSTOM_FUNCTIONS========

# === | ALIAS | ===
alias zshrc="vim ~/.zshrc"
alias szshrc='source ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias svimrc='source ~/.vimrc'
alias ohmyzsh="vim ~/.oh-my-zsh"
alias trc='tree -C'
alias trp='tree -Cpu'
alias trd='tree -C -d'
alias clc='clear'
alias weather='curl wttr.in/Minsk'
alias subl='open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias rm='rmtrash' 
alias rand='cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 32 | head -n'
#alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'

#========Exports=========
#
export MANPATH="/usr/local/man:$MANPATH"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

