# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "jenkins"

    config.vm.network :private_network, ip: "192.168.10.19"
    config.vm.network:forwarded_port,guest:80,host:8080,auto_correct:true
    config.vm.network:forwarded_port,guest:8080,host:8090,auto_correct:true

    config.vm.synced_folder "./Share-Jenkins", "/Share-Jenkins", mount_options: ['dmode=777', 'fmode=777']
    
    config.vm.provider 'virtualvm' do |v|
            v.memory = "1248"
            v.name = "Jenkins-Vm"
    end
    config.vm.provision "shell", path: "../provisioning/boot-Jenkins.sh"
end
