# =================================
# .zshrc Configuration
# =================================

# Define environment variables
export ZSH=$HOME/.oh-my-zsh
export TERM="screen-256color"  # Terminal type and color
export LS_COLORS=$LS_COLORS:'di=1;35:'
export COLORTERM="truecolor"  # Allows terminal to use the true colors.
export EDITOR="nvim"  # Set vim as the default editor
export MANPATH="/usr/local/man"  # Man pages directory
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:$HOME/bin"
export PYENV_ROOT="$HOME/.pyenv"
export GCLOUD_PATH='/Users/antonmaslakov/.gcloud-sdk'
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export PATH=$JAVA_HOME/bin:$PATH

# Define aliases
alias zshrc="vim ~/.zshrc"
alias szshrc='source ~/.zshrc'
alias tmuxrc='vim ~/.tmux.conf'
alias vim='nvim'
alias v='vim'
alias vimrc='vim ~/.config/nvim/lua/config.lua'
alias sshconf='vim ~/.ssh/config'
alias k='kubectl'
alias cat='bat'
alias trc='tree -C'
alias trp='tree -Cpu'
alias trd='tree -C -d'
alias free_space='diskutil info / | grep "Free"'
alias pip='pip3'
alias python='python3'
alias weather='curl wttr.in'
alias ip='curl ifconfig.co'
alias local-ip='ipconfig getifaddr en0'
alias tf='terraform'
alias subl='open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias l="exa -la --group-directories-first"

### 
alias wr='cd ~/Workspace/repos/'
alias kh='cd ~/Workspace/repos/kitchenhub'
alias da='cd ~/Workspace/repos/DA'
alias balik='cd ~/Workspace/repos/balik'


# ZSH plugins
plugins=(
  git
  aws
  gcloud
  terraform
  docker
  dotenv
  npm
  ssh-agent
  systemd
  pre-commit
  virtualenv
  vscode
  httpie
  zsh-vi-mode
  tmux
  tmux-cssh
  zsh-interactive-cd
  zsh-autosuggestions
  zsh-syntax-highlighting
  1password
)

# Use Oh-My-Zsh as shell
source $ZSH/oh-my-zsh.sh

# Resolve zsh-vi-mode unable to use ZSH: 
zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BEAM
export ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
export ZVM_OPPEND_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE

# ZSH settings
unsetopt inc_append_history  # No appending to history file
unsetopt share_history  # No shared history
setopt CHECK_JOBS  # Alert if background jobs are running
setopt NOTIFY  # Info about background jobs

# FZF settings
export FZF_DEFAULT_OPTS='--height 50% --layout=reverse --border'

# Customized cd command for directory navigation with fzf
function cd() {
    if [[ "$#" != 0 ]]; then
        builtin cd "$@";
        return
    fi
    while true; do
        local lsd=$(echo ".." && ls -p | grep '/$' | sed 's;/$;;')
        local dir="$(printf '%s\n' "${lsd[@]}" |
            fzf --reverse --preview '
                __cd_nxt="$(echo {})";
                __cd_path="$(echo $(pwd)/${__cd_nxt} | sed "s;//;/;")";
                echo $__cd_path;
                echo;
                ls -p --color=always "${__cd_path}";
        ')"
        [[ ${#dir} != 0 ]] || return 0
        builtin cd "$dir" &> /dev/null
    done
}

# Additional tooling for the ZSH configuration
zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# GCloud SDK settings
if [ -f "$GCLOUD_PATH/path.zsh.inc" ]; then . "$GCLOUD_PATH/path.zsh.inc"; fi
if [ -f "$GCLOUD_PATH/completion.zsh.inc" ]; then . "$GCLOUD_PATH/completion.zsh.inc"; fi

# Pyenv virtualenv settings
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Initialize Starship, a cross-shell prompt
eval "$(starship init zsh)"

